# Generated by Django 5.2 on 2025-05-18 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reviewRating',
            new_name='review_rating',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.professional'),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_services', to='account.professional'),
        ),
    ]
