# Generated by Django 5.2 on 2025-05-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_reviews_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='date',
            new_name='date_posted',
        ),
    ]
