# Generated by Django 5.2 on 2025-05-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_date_reviews_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='professional',
            name='office_location',
        ),
        migrations.AddField(
            model_name='professional',
            name='office_location',
            field=models.ManyToManyField(to='account.officelocations'),
        ),
    ]
