# Generated by Django 5.2 on 2025-05-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_officelocations_remove_professional_office_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='office_location',
        ),
        migrations.AddField(
            model_name='officelocations',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.professional'),
        ),
    ]
