# Generated by Django 5.2 on 2025-05-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_professional_office_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officelocations',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.professional'),
        ),
    ]
