# Generated by Django 5.2 on 2025-06-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_officelocations_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocations',
            name='city',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='officelocations',
            name='postal_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='officelocations',
            name='provice',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='officelocations',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
