# Generated by Django 5.2 on 2025-06-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_officelocations_city_officelocations_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officelocations',
            old_name='provice',
            new_name='province',
        ),
    ]
