# Generated by Django 5.2 on 2025-06-05 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_provice_officelocations_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedetails',
            name='end_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
