# Generated by Django 5.2 on 2025-06-05 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_experiencedetails_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedetails',
            name='end_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
