# Generated by Django 5.2 on 2025-06-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_experiencedetails_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedetails',
            name='end_year',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='start_year',
            field=models.IntegerField(max_length=4),
        ),
    ]
