# Generated by Django 5.2 on 2025-06-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_experiencedetails_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedetails',
            name='end_year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
