# Generated by Django 5.2 on 2025-05-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateTimeField()),
                ('post_title', models.CharField(max_length=1000)),
                ('post_content', models.TextField()),
                ('post_views', models.IntegerField()),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
            ],
        ),
        migrations.CreateModel(
            name='ForumAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_responded', models.DateTimeField()),
                ('answer_content', models.TextField()),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.professional')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumquestion')),
            ],
        ),
    ]
