# Generated by Django 5.2 on 2025-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_questiontags'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='post_tags',
            field=models.ManyToManyField(related_name='tag_names', to='forum.questiontags'),
        ),
    ]
