# Generated by Django 5.2 on 2025-05-20 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='dealStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='clientDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
                ('deal_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_portal.dealstage')),
            ],
        ),
    ]
