# Generated by Django 5.2 on 2025-05-22 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0002_servicestype_clientdeal_professional_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_service_items', to='user_portal.servicedetails')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_portal.servicestype')),
            ],
        ),
    ]
