# Generated by Django 5.2 on 2025-05-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0003_requestedservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetails',
            name='requested_services',
        ),
    ]
