# Generated by Django 5.2 on 2025-05-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0004_remove_servicedetails_requested_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='requested_services',
            field=models.ManyToManyField(related_name='service_details', through='user_portal.RequestedService', to='user_portal.servicestype'),
        ),
    ]
