# Generated by Django 5.2 on 2025-05-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0005_servicedetails_requested_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdeal',
            name='date_initiated',
            field=models.DateTimeField(null=True),
        ),
    ]
