# Generated by Django 5.2 on 2025-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0006_clientdeal_date_initiated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdeal',
            name='date_initiated',
            field=models.DateTimeField(default='2024-01-01 12:00:00'),
            preserve_default=False,
        ),
    ]
