# Generated by Django 5.2 on 2025-05-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0007_alter_clientdeal_date_initiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdeal',
            name='deletion_date',
            field=models.DateTimeField(null=True),
        ),
    ]
