# Generated by Django 5.2 on 2025-05-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0008_clientdeal_deletion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdeal',
            name='completion_date',
            field=models.DateTimeField(null=True),
        ),
    ]
