# Generated by Django 5.2 on 2025-05-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0009_clientdeal_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdeal',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdeal',
            name='deletion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
