# Generated by Django 5.2 on 2025-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0010_alter_clientdeal_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdocument',
            name='file',
            field=models.FileField(upload_to='deal_documents/'),
        ),
    ]
