# Generated by Django 5.2 on 2025-05-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0011_alter_dealdocument_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdeal',
            name='deletion_date',
        ),
    ]
